### ISSUE TITLE
Blocking issues?

### ISSUE THREAD

**Issue by timholy** [JuliaIO/QuartzImageIO.jl#10]
I'd really like to tag a new version of Images, but remaining concerns about this package are the main blocker. I haven't been able to follow everything due to a schedule crunch over the last few days, but if I remember correctly it's been decided that the name is going to stay unchanged. If so, that is no longer a concern.

Is [this](https://github.com/JuliaIO/FileIO.jl/issues/42#issuecomment-144838930) the only remaining issue? If so, presumably we need to finish & merge https://github.com/JuliaIO/FileIO.jl/pull/43.

**Comment by rsrock** [comment]
Naming is no longer an issue.  That ship seems to have sailed.  Besides, I don't have any packages that start with "Q", so this claims prime tab-complete real estate.  Contrast that with "image<tab>", which has Images, ImageView, ImageMagick, and (for me) ImageJ. :smile: 

But the big problem is JuliaIO/FileIO.jl#43, and the set of default readers.  I wouldn't tag until that's resolved.  Right now, this package is just about impossible to debug, because FileIO is currently too helpful (!).  I just added all of those additional test images to cover a couple of untested paths, and my coverage went down instead of up. That's because some sort of bug is causing QuartzImageIO to fail silently and ImageMagick to take over.

I also need a way of testing this on Travis without pulling down ImageMagick.  That means we have to add `@linux ImageMagick` and `@windows ImageMagick` to Images's REQUIRE.

**Comment by timholy** [comment]
Once we finish JuliaIO/FileIO.jl#43, I think we can remove those from Images' REQUIRE.

**Comment by timholy** [comment]
I've tagged a new Images, but I'll leave it up to you to decide when to tag a new version of this package.

**Comment by rsrock** [comment]
Thanks Tim, looks like it's ready
