### ISSUE TITLE
Image is all green

### ISSUE THREAD

**Issue by SimonDanisch** [JuliaIO/QuartzImageIO.jl#30]
Sorry for the very unspecific issue, but I want to keep track of this and I didn't want to miss out on the chance that someone has a quick idea about where that can come from.
I can upload the photo if necessary!

**Comment by rsrock** [comment]
Yes, please upload the photo.

I assume this is when loading, and not after a save-load cycle? All green is certainly strange, if anything would go wrong I'd expect it to be with the first or the last color channel, not the middle one!

**Comment by SimonDanisch** [comment]
Here you go:
https://raw.githubusercontent.com/SimonDanisch/MIT18065/master/demos/photostitching/law1.jpg

**Comment by rsrock** [comment]
I see the same thing-- I'll look into it

**Comment by SimonDanisch** [comment]
thanks a lot!

**Comment by rsrock** [comment]
This is happening to you through Jupyter or some other MIME display, correct?  Does it look normal for you with `using ImageView; imshow(img)`?  It does for me, except for the coordinate flip.  The images also look correct when saving to a file.  I think that narrows it down to something in the streaming path.

**Comment by timholy** [comment]
FYI on Linux with ImageMagick I don't see the flip:
```julia
julia> img = load("law1.jpg");

julia> summary(img)
"1456×2592 Array{RGB{N0f8},2}"

julia> ImageView.imshow(img)
# it's in the correct orientation
```

**Comment by rsrock** [comment]
Yeah, I think the orientation is a separate issue.  

If I check the temporary file that's generated here:

https://github.com/JuliaIO/QuartzImageIO.jl/blob/4c19585a1fa29685302c5d354ab1c63f93e1f980/src/QuartzImageIO.jl#L313

Then I get our little green monster.  And I do mean little, the image size is cut in half in each dimension.

It's weird, because I can save this to a PNG just fine (correct size, correct colors), and I've ruled out `clamp01nan` as the culprit.  Perhaps something with `restrict`?  I tested in Jupyter with smaller images, perhaps they weren't large enough to trigger the resizing?

I'll have to look into this more later...

**Comment by SimonDanisch** [comment]
Oh yeah I remember writemime resizing... Where is that code for that again? :D

**Comment by timholy** [comment]
https://github.com/JuliaImages/Images.jl/blob/master/src/showmime.jl

**Comment by rsrock** [comment]
Yep, that's where the problem lies.  PR on it's way

**Comment by rsrock** [comment]
...not so fast.

The real issue here is twofold.  First, `(restrict)` is converting the img from a RGB4{N0f8} to a RGB4{Float32}.  I don't think it needs to do that (strictly speaking).  The second is that I have not written the `save`rs for float images yet.

**Comment by timholy** [comment]
Perhaps `restrict` should have an extra signature `restrict(RGB{N0f8}, img)` for easy control over the output element type. Or maybe even `restrict(f, img)` where `f` is applied to each element before stashing the result. One could call `f` on the [test point](https://github.com/JuliaImages/Images.jl/blob/f408a21365c6b70c93252bdcb6911a507ccc4918/src/algorithms.jl#L555) to determine the output type.

In principle I don't mind the idea of returning the same element type, but it's worth thinking about what happens with `rand(UInt8, 5, 5)` and `randbool(5, 5)`. (Because `N0f8` mimics floating-point numbers, it "rounds" but `UInt8` will not.)

**Comment by SimonDanisch** [comment]
You said something about Images being flipped... Is that tracked somewhere? I just run into it as well.

**Comment by rsrock** [comment]
There's no issue for flipped images yet, feel free to start one.  I think there were some changes around the loader with the new Images that I need to look into.

I'm implementing saving Float32 images.  Now I have a magenta image.  Progress, I suppose 😄

**Comment by SimonDanisch** [comment]
Bump :) is there anything I can help with?

**Comment by rsrock** [comment]
A temporary solution is to comment out these lines:

https://github.com/JuliaImages/Images.jl/blob/f408a21365c6b70c93252bdcb6911a507ccc4918/src/showmime.jl#L20-L22

I haven't had a chance yet to figure out why one of the color channels is getting crushed.

**Comment by rsrock** [comment]
Ok, @SimonDanisch, see if the rsr/floatsave branch helps you.

**Comment by SimonDanisch** [comment]
Sorry, I don't have an apple device anymore. But I'm sure it'll be fixed, when it works for you now ;)
It should be possible to create a test for this, no?
